### PR TITLE
define, use and document higher-level spacing macros

### PR DESCRIPTION
**Pull request by gasche**
``` latex
\newcommand{\lete}[5]{%
  \kwopen{#2{let}}%
  #3%
  \mathbin{#1{=}}%
  #4%
  \kwbin{#2{in}}%
  #5%
}

\newcommand{\unfolde}[3]{\kwinfix{#2{unfold}} #3}
```

### CODE REVIEW

**Comment by gasche** [comment]
The risk of "regression" (having stuff look worse than before to your taste) of the change is relatively high, because I tried to stay within a small subset of spacing combinators and it only approximates the previous spacing choices. On the other hand, this gives a form of consistency for free: in particular now the spacing of keywords is always the same for the various constructions -- it used to be larger for `if then else` than around of the `in` of `let x = e1 in e2` for example, and that does not seem very justified.

**Comment by wilbowma** [comment]
A screenshot comparing the output; this pull request on the left, old on the right.
screenshot_2016-06-04_16-12-35

**Comment by wilbowma** [comment]
The new version seems to save a bit of space over all, which is good, and looks better in many cases. I'm a little unsure of how the if-then-else form looks; it seems a little cramped to me. 

Might want to get feedback from other users before merging.

**Comment by wilbowma** [comment]
Related to #27

**Comment by wilbowma** [comment]
Should these changes apply to things like the judgment forms, logical relations, and meta-language stuff (e.g. `\bnfalt`)?

**Comment by gasche** [comment]
Note that I kept the spacing after the `\lambda` or `\forall` in the polyfun case (it looked like an intentional design choice), but I'm personally a bit sceptical that this is the right choice -- I would rather use `\mathopen` than `\mathpunct` in this case, with no spacing.

I do agree that `if then else` feels a bit cramped, but then I'm not sure that we have a justification for having large spacing there that around, say, pack's `as` keyword. We could use `\:` or `\` for keyword spacing across the board, which would be consistent but take more space.

**Comment by gasche** [comment]
> Should these changes apply to things like the judgment forms, logical relations, and meta-language stuff (e.g. \bnfalt)?

I guess so; the `\vdash` should be mathrel, and the semantic brackets could be math{open,close}. I can send further commits for that.

**Comment by wilbowma** [comment]
I think the polyfun and fun macros should be consistent; no spacing might be fine. 

Frankly, the spacing conventions we had before were "organic", as they say, so I'm fine with suggestions that are based in consistency and reason.

**Comment by gasche** [comment]
I rebased the PR with spacing classes for the judgment combinators as well. Not all of them (and no BNF) were present in the test file, so the first commit of the PR adds them to the test file.

**Comment by wilbowma** [comment]
New comparison
screenshot_2016-06-04_17-16-56

**Comment by wilbowma** [comment]
Looks good; thanks for the work.

I'll ask for comments from my few users and see what they think. I'll also rebuild our latest paper that uses mttex and compare.

**Comment by wilbowma** [comment]
I just went through our fabcc paper with this branch; it looks a lot better. 

Unfortunately, we also use a lot of things not in mttex, or override mttex defaults. The observant reader will notice some inconsistent spacing.

**Comment by wilbowma** [comment]
To be fair, all I would need to do is redefine the macros using your spacing macros, so it's not a criticism of this feature.

**Pull request closed without merging**
